format = """
[ ](fg:fg bg:terminal_dark)\
$os\
[î‚±](fg:fg bg:terminal_dark)\
$directory\
[î‚±](fg:fg bg:terminal_dark)\
$git_branch\
$git_status\
[î‚°](fg:terminal_dark)\
\n$character"""


right_format = """
[î‚²](fg:terminal_dark)\
$cmd_duration\
$conda\
$dart\
$golang\
$nix_shell\
$nodejs\
$php\
$python\
$rust\
$username\
$hostname"""

palette = "tokyonight"

[palettes.tokyonight]
"bg_dark" = "#1f2335"
"bg" = "#24283b"
"bg_highlight" = "#292e42"
"terminal_black" = "#414868"
"terminal_dark" = "#303030"
"fg" = "#c0caf5"
"fg_dark" = "#a9b1d6"
"fg_gutter" = "#3b4261"
"dark3" = "#545c7e"
"comment" = "#565f89"
"dark5" = "#737aa2"
"blue0" = "#3d59a1"
"blue" = "#7aa2f7"
"cyan" = "#7dcfff"
"blue1" = "#2ac3de"
"blue2" = "#0db9d7"
"blue5" = "#89ddff"
"blue6" = "#b4f9f8"
"blue7" = "#394b70"
"magenta" = "#bb9af7"
"magenta2" = "#ff007c"
"purple" = "#9d7cd8"
"orange" = "#ff9e64"
"yellow" = "#e0af68"
"green" = "#9ece6a"
"green1" = "#73daca"
"green2" = "#41a6b5"
"teal" = "#1abc9c"
"red" = "#f7768e"
"red1" = "#db4b4b"
"git_change" = "#6183bb"
"git_add" = "#449dab"
"git_delete" = "#914c54"

[hostname]
ssh_only = true
format = '[$ssh_symbol$hostname ]($style)'
style = "fg:fg bg:terminal_dark"

[username]
style_root = "fg:magenta2 bg:terminal_dark"
style_user = "fg:fg bg:terminal_dark"
format = "[î‚³ $user/]($style)"
show_always = false

[cmd_duration]
min_time = 2000
style = "fg:fg bg:terminal_dark"
format = "[î‚³ ó±¦Ÿ took $duration ]($style)"

[git_branch]
symbol = "ï˜ "
style = "fg:green1 bg:terminal_dark"
format = '[ $symbol$branch ]($style)'

[git_metrics]
added_style = "fg:green1 bg:terminal_dark"
deleted_style = "fg:red bg:terminal_dark"
format = "([+$added ]($added_style))([-$deleted]($deleted_style) )"
disabled = false

[git_status]
style = "bg:terminal_dark"
ahead = 'â‡¡${count}'
behind = 'â‡£${count}'
conflicted = "=${count}"
deleted = "âœ˜${count}"
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
modified = "!${count}"
renamed = "Â»${count}"
staged = "+${count}"
stashed = "$${count}"
untracked = "?${count}"
format = '[[($all_status$ahead_behind )](fg:yellow bg:terminal_dark)]($style)'
windows_starship = '/mnt/c/Users/username/scoop/apps/starship/current/starship.exe'

[time]
disabled = false
time_format = "%R"                                      # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ ïº $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[aws]
symbol = "îŒ½  "
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[azure]
disabled = true
format = '[$symbol($subscription)]($style) '
symbol = 'ï´ƒ '
style = "fg:fg bg:terminal_dark"

[buf]
symbol = "ï’ "
style = "fg:fg bg:terminal_dark"

[c]
symbol = "î˜ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[conda]
symbol = "ï„Œ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[dart]
symbol = "î˜ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[directory]
read_only = " ï€£"
read_only_style = "fg:magenta2 bg:terminal_dark"
style = "fg:cyan bg:terminal_dark"
format = '[ î—¾ $path]($style)[$read_only ]($read_only_style)'
truncation_length = 0
truncate_to_repo = false
truncation_symbol = "â€¦/"

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[fossil_branch]
symbol = "ï˜ "
style = "fg:fg bg:terminal_dark"
format = '[$symbol$branch]($style)'

[golang]
symbol = "ï³‘"
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[guix_shell]
symbol = "ïŒ¥ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[haskell]
symbol = "î· "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[haxe]
symbol = "âŒ˜ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[hg_branch]
symbol = "ï˜ "
style = "fg:fg bg:terminal_dark"
format = '[$symbol$branch(:$topic) ]($style)'

[java]
symbol = "î‰– "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[lua]
symbol = "î˜  "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[memory_usage]
symbol = "ó°› "

[meson]
symbol = "â¬¢ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[nix_shell]
symbol = "ïŒ“ "
style = "bg:terminal_dark"
heuristic = true
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[nodejs]
symbol = "îœ˜ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[os]
style = "fg:fg bg:terminal_dark"
disabled = false

[os.symbols]
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "ï…» "
Arch = "ïŒƒ "
CentOS = "ïŒ„ "
Debian = "ïŒ† "
DragonFly = "îŠ "
Emscripten = "ïˆ… "
EndeavourOS = "ï†— "
Fedora = "ïŒŠ "
FreeBSD = "ïŒŒ "
Garuda = "ï¯‘ "
Gentoo = "ïŒ "
HardenedBSD = "ï²Š "
Illumos = "ïœ· "
Linux = "ïŒš "
Macos = "ïŒ‚ "
Manjaro = "ïŒ’ "
Mariner = "ï‡ "
MidnightBSD = "ï†† "
Mint = "ïŒ "
NetBSD = "ï€¤ "
NixOS = "ïŒ“ "
OpenBSD = "ïœ¹ "
openSUSE = "ïŒ” "
OracleLinux = "ó°‚¹ "
Pop = "îŠ£ "
Raspbian = "ïŒ• "
Redhat = "ïŒ– "
RedHatEnterprise = "ïŒ– "
Redox = "ï”— "
Solus = "ï´± "
SUSE = "ïŒ” "
Ubuntu = "ïŒ› "
Unknown = "ïˆ­ "
Windows = "ï…º "

[package]
symbol = "ó°— "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[pijul_channel]
symbol = "ï˜ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[python]
symbol = "îˆµ "
style = "fg:fg bg:terminal_dark"
format = '[î‚³ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\))]($style)'

[rlang]
symbol = "ï³’ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[ruby]
symbol = "î‘ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[rust]
symbol = "î¨ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[scala]
symbol = "îœ· "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'

[spack]
symbol = "ğŸ…¢ "
style = "bg:terminal_dark"
format = '[[î‚³ $symbol ($version) ](fg:fg bg:terminal_dark)]($style)'
