####################################################################################################
# For linux
####################################################################################################
[linux.users."kobayashi.sumiharu.r4"]
externals = ["blesh", "fzf-options", "lesspipe", "tpm"]
[linux.users."kobayashi.sumiharu.r4".sops]
"pkgs/ai-tools/env" = ".env"
"pkgs/ssh/univ" = ".ssh/conf.d/hosts/univ"

[linux.users."kobayashi.sumiharu.r4".env]
initExtra = ""
extraConfig = """
if [ "$SHELL" != "/usr/bin/zsh" ] && [ "${LOGIN:-1}" -eq 1 ]; then
  exec /usr/bin/zsh -l
fi
"""
PATH = ["$HOME/bin", "$HOME/.local/bin", "$HOME/.local/share/mcp-servers/bin"]
[linux.users."kobayashi.sumiharu.r4".packages.mcpServers.node] # name = "package_name", name is executable name
mcp-server-filesystem = "@modelcontextprotocol/server-filesystem"
mcp-server-memory = "@modelcontextprotocol/server-memory"
mcp-server-sequential-thinking = "@modelcontextprotocol/server-sequential-thinking"
context7-mcp = "@upstash/context7-mcp"
copilot = "@github/copilot"
gemini = "@google/gemini-cli"
mcp-hub = "mcp-hub@latest"
[linux.users."kobayashi.sumiharu.r4".packages.mcpServers.pip] # name = "module_name", name is executable name
mcp-server-git = "mcp_server_git"
mcp-nixos = "mcp_nixos"
[linux.users."kobayashi.sumiharu.r4".packages.mcpServers.github.github-mcp-server] # name = "module_name", name is executable name
owner = "github"
repo = "github-mcp-server"
srcFile = "github-mcp-server_Windows_x86_64.zip"
exeFile = "github-mcp-server.exe"
[linux.users."kobayashi.sumiharu.r4".env.export]
EDITOR = "nvim"
FZF_ALT_C_COMMAND = "fd --type d"
FZF_ALT_C_OPTS = "--preview 'tree -C {} | tree -200'"
FZF_CTRL_R_OPTS = "--preview 'echo {}' --preview-window up:3:hidden:wrap --bind 'ctrl-/:toggle-preview' --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort' --color header:italic --header 'Press CTRL-Y to copy command into clipboard'"
FZF_CTRL_T_COMMAND = "fd --type f"
FZF_CTRL_T_OPTS = "--preview 'bat -n --color: always {}' --bind 'ctrl-/:change-preview-window(down|hidden|)'"
FZF_TMUX = "1"
FZF_TMUX_OPTS = "-p -w 80% -h 70%"
JQ_COLORS = "1;30:0;37:0;37:0;37:0;32:1;37:1;37"
LG_CONFIG_FILE = "$XDG_CONFIG_HOME/lazygit/config.yml"
MANPAGER = "sh -c 'sed -u -e \\\"s%\\\\x1B\\[[0-9;]*m%%g; s%.\\\\x08%%g\\\" | bat -p -lman'"
TMUX_TMPDIR = "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
LD_LIBRARY_PATH = "$(find /disk/fs1/soft/cuda/cuda-* -maxdepth 1 -name \"lib64\" -exec printf \"%s:\" {} + | sed 's/:$//'):$LD_LIBRARY_PATH"
CUDA_HOME = "/disk/fs1/soft/cuda/cuda-12.4.1_cudnn-9.2.0.82/lib64"
LESSOPEN = "|lesspipe %s"
LANG = "en-US.UTF-8"
LANGUAGE = "en_US"
LC_ALL = "en_US.UTF-8"

[linux.users."kobayashi.sumiharu.r4".env.alias]
copilot = "wrapEnv copilot"
mcp-hub = "wrapEnv mcp-hub"

[linux.users."kobayashi.sumiharu.r4".packages.mise.settings]
idiomatic_version_file = true
always_keep_download = false
always_keep_install = false
plugin_autoupdate_last_check_duration = "1 week"
verbose = false
http_timeout = "30s"
jobs = 4
raw = false
yes = false
not_found_auto_install = true
auto_install = true
experimental = true
idiomatic_version_file_enable_tools = []
[linux.users.sumi.packages.mise.plugins]
neovim = "asdf:neovim"
[linux.users."kobayashi.sumiharu.r4".packages.mise.tools]
bat = "latest"
btop = "latest"
cmake = "latest"
delta = "latest"
deno = "latest"
duf = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
go = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
python = "latest"
ripgrep = "latest"
sops = "latest"
starship = "latest"
tmux = "3.3"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
yt-dlp = "latest"
zoxide = "latest"
