"$schema" = "https://yazi-rs.github.io/schemas/theme.json"
[app]
overall = { bg = "#1e2030"}

[mgr]
cwd = { fg = "#828bb8", italic = true }

# Find
find_keyword  = { fg = "#1e2030", bg = "#ff966c", bold = true }
find_position = { fg = "#0db9d7", bg = "#203346", bold = true }

# Symlink
symlink_target = {italic = true}

# Marker
marker_copied   = { fg = "#c3e88d", bg = "#c3e88d" }
marker_cut      = { fg = "#ff757f", bg = "#ff757f" }
marker_marked   = { fg = "#c099ff", bg = "#c099ff" }
marker_selected = { fg = "#82aaff", bg = "#82aaff" }

# Count
count_copied   = { fg = "#1e2030", bg = "#c3e88d" }
count_cut      = { fg = "#1e2030", bg = "#ff757f" }
count_selected = { fg = "#1e2030", bg = "#82aaff" }

# Border
border_symbol = "│"
border_style  = { fg = "#589ed7" }

# NOTE: can be combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

# Tab
[tabs]
active   = { fg = "#1b1d2b", bg = "#82aaff" }
inactive = { fg = "#82aaff", bg = "#3b4261" }

[mode]
normal_main = { fg = "#1b1d2b", bg = "#82aaff", bold = true }
normal_alt  = { fg = "#82aaff", bg = "#3b4261" }

select_main = { fg = "#1b1d2b", bg = "#c099ff", bold = true }
select_alt  = { fg = "#c099ff", bg = "#3b4261" }

unset_main  = { fg = "#1b1d2b", bg = "#fca7ea", bold = true }
unset_alt   = { fg = "#fca7ea", bg = "#3b4261" }

# Hover
[indicator]
parent         = { bg = "#2f334d" }
current         = { bg = "#2f334d" }
preview = { bg = "#2f334d" }

[status]
overall   = { fg = "#c8d3f5", bg = "#1e2030" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_type  = { fg = "#82aaff" }
perm_read  = { fg = "#ffc777" }
perm_write = { fg = "#ff757f" }
perm_exec  = { fg = "#c3e88d" }
perm_sep   = { fg = "#444a73" }

# Progress
progress_label  = { fg = "#c8d3f5", bold = true }
progress_normal = { fg = "#3e68d7", bg = "#2f334d" }
progress_error  = { fg = "#c53b53", bg = "#2f334d" }

# Which
[which]
cols            = 3
mask            = { bg = "#1e2030" }
cand            = { fg = "#86e1fc" }
rest            = { fg = "#82aaff" }
desc            = { fg = "#c099ff" }
separator       = " ➜ "
separator_style = { fg = "#636da6" }

# Confirm
[confirm]
border  = { fg = "#0db9d7" }
title   = { fg = "#589ed7" }
body = {}
list    = {}
btn_yes = { bg = "#2d3f76" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spottter
[spot]
border  = { fg = "#589ed7" }
title   = { fg = "#589ed7" }

# Notification
[notify]
title_info  = { fg = "#0db9d7" }
title_warn  = { fg = "#ffc777" }
title_error = { fg = "#c53b53" }

# Icons
icon_info = ""
icon_warn = ""
icon_error = ""

# Picker
[pick]
border   = { fg = "#589ed7" }
active   = { fg = "#c8d3f5",  bg = "#2d3f76" }
inactive = { fg = "#c8d3f5" }

# Input
[input]
border   = { fg = "#0db9d7" }
title    = { fg = "#0db9d7" }
value    = { fg = "#fca7ea" }
selected = { bg = "#2d3f76" }

# Completion
[cmp]
border   = { fg = "#0db9d7" }
active   = { fg = "#c8d3f5", bg = "#363c58" }
inactive = { fg = "#c8d3f5" }

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# Task manager
[tasks]
border  = { fg = "#589ed7" }
title   = { fg = "#589ed7" }
hovered = { fg = "#c8d3f5", bg = "#2d3f76" }

# Help menu
[help]
on      = { fg = "#c3e88d" }
run     = { fg = "#c099ff" }
desc    = { fg = "#86e1fc" }
hovered = { bg = "#2f334d" }
footer  = { fg = "#c8d3f5", bg = "#222436" }

# File-specific styles
[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#ffc777" },

	# Media
	{ mime = "{audio,video}/*", fg = "#c099ff" },

	# Archives
	{ mime = "application/*zip", fg = "#ff757f" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ff757f" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#86e1fc" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#ff757f" },

	# Special files
	{ url = "*", is = "orphan", bg = "#ff757f" },
	{ url = "*", is = "exec"  , fg = "#c3e88d" },

	# Fallback
	{ url = "*/", fg = "#82aaff" },
	{ url = "*", fg = "#c8d3f5" }
]
    