"$schema" = "https://yazi-rs.github.io/schemas/theme.json"
[app]
overall = { bg = "#d0d5e3"}

[mgr]
cwd = { fg = "#6172b0", italic = true }

# Find
find_keyword  = { fg = "#d0d5e3", bg = "#b15c00", bold = true }
find_position = { fg = "#07879d", bg = "#cbd9e0", bold = true }

# Symlink
symlink_target = {italic = true}

# Marker
marker_copied   = { fg = "#587539", bg = "#587539" }
marker_cut      = { fg = "#f52a65", bg = "#f52a65" }
marker_marked   = { fg = "#9854f1", bg = "#9854f1" }
marker_selected = { fg = "#2e7de9", bg = "#2e7de9" }

# Count
count_copied   = { fg = "#d0d5e3", bg = "#587539" }
count_cut      = { fg = "#d0d5e3", bg = "#f52a65" }
count_selected = { fg = "#d0d5e3", bg = "#2e7de9" }

# Border
border_symbol = "│"
border_style  = { fg = "#4094a3" }

# NOTE: can be combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

# Tab
[tabs]
active   = { fg = "#b4b5b9", bg = "#2e7de9" }
inactive = { fg = "#2e7de9", bg = "#a8aecb" }

[mode]
normal_main = { fg = "#b4b5b9", bg = "#2e7de9", bold = true }
normal_alt  = { fg = "#2e7de9", bg = "#a8aecb" }

select_main = { fg = "#b4b5b9", bg = "#9854f1", bold = true }
select_alt  = { fg = "#9854f1", bg = "#a8aecb" }

unset_main  = { fg = "#b4b5b9", bg = "#7847bd", bold = true }
unset_alt   = { fg = "#7847bd", bg = "#a8aecb" }

# Hover
[indicator]
parent         = { bg = "#c4c8da" }
current         = { bg = "#c4c8da" }
preview = { bg = "#c4c8da" }

[status]
overall   = { fg = "#3760bf", bg = "#d0d5e3" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_type  = { fg = "#2e7de9" }
perm_read  = { fg = "#8c6c3e" }
perm_write = { fg = "#f52a65" }
perm_exec  = { fg = "#587539" }
perm_sep   = { fg = "#a1a6c5" }

# Progress
progress_label  = { fg = "#3760bf", bold = true }
progress_normal = { fg = "#7890dd", bg = "#c4c8da" }
progress_error  = { fg = "#c64343", bg = "#c4c8da" }

# Which
[which]
cols            = 3
mask            = { bg = "#d0d5e3" }
cand            = { fg = "#007197" }
rest            = { fg = "#2e7de9" }
desc            = { fg = "#9854f1" }
separator       = " ➜ "
separator_style = { fg = "#848cb5" }

# Confirm
[confirm]
border  = { fg = "#07879d" }
title   = { fg = "#4094a3" }
body = {}
list    = {}
btn_yes = { bg = "#b7c1e3" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spottter
[spot]
border  = { fg = "#4094a3" }
title   = { fg = "#4094a3" }

# Notification
[notify]
title_info  = { fg = "#07879d" }
title_warn  = { fg = "#8c6c3e" }
title_error = { fg = "#c64343" }

# Icons
icon_info = ""
icon_warn = ""
icon_error = ""

# Picker
[pick]
border   = { fg = "#4094a3" }
active   = { fg = "#3760bf",  bg = "#b7c1e3" }
inactive = { fg = "#3760bf" }

# Input
[input]
border   = { fg = "#07879d" }
title    = { fg = "#07879d" }
value    = { fg = "#7847bd" }
selected = { bg = "#b7c1e3" }

# Completion
[cmp]
border   = { fg = "#07879d" }
active   = { fg = "#3760bf", bg = "#b3b8d1" }
inactive = { fg = "#3760bf" }

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""

# Task manager
[tasks]
border  = { fg = "#4094a3" }
title   = { fg = "#4094a3" }
hovered = { fg = "#3760bf", bg = "#b7c1e3" }

# Help menu
[help]
on      = { fg = "#587539" }
run     = { fg = "#9854f1" }
desc    = { fg = "#007197" }
hovered = { bg = "#c4c8da" }
footer  = { fg = "#3760bf", bg = "#e1e2e7" }

# File-specific styles
[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#8c6c3e" },

	# Media
	{ mime = "{audio,video}/*", fg = "#9854f1" },

	# Archives
	{ mime = "application/*zip", fg = "#f52a65" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#f52a65" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#007197" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#f52a65" },

	# Special files
	{ url = "*", is = "orphan", bg = "#f52a65" },
	{ url = "*", is = "exec"  , fg = "#587539" },

	# Fallback
	{ url = "*/", fg = "#2e7de9" },
	{ url = "*", fg = "#3760bf" }
]
    