name: Auto approve
on:
  workflow_run:
    workflows: [Build check]
    types:
      - completed

jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      pr-number: ${{ steps.pr-number.outputs.pr-number }}
      check-codeowner: >-
        steps.pr-author.outputs.pr-author == "misumisumi" ||
        steps.pr-author.outputs.pr-author == "app/operate-pr-for-flakes"
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: build-check.yml
          workflow_conclusion: success
          name: pr-number
          path: artifacts

      - name: Set PR number
        id: pr-number
        run: |
          echo pr-number=$(cat ./artifacts/pr-number.txt) >> $GITHUB_OUTPUT

      - name: Check PR Author
        id: pr-author
        run: |
          echo pr-author=$(gh pr view ${{ steps.pr-number.outputs.pr-number }} --json author --jq .author.login) >> $GITHUB_OUTPUT

  on-success:
    runs-on: ubuntu-latest
    needs: check-pr
    if: >-
      needs.outputs.check-codeowner &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: PR review and merge
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr review --approve ${{ needs.check-pr.outputs.pr-number.outputs.pr-number }}
          gh pr merge --merge --auto ${{ needs.check-pr.outputs.pr-number.outputs.pr-number }}
