name: Auto release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
jobs:
  user-pr:
    runs-on: ubuntu-latest
    if: ${{  github.actor == 'release-please-action[bot]' || ! endsWith(github.actor, '[bot]') }}
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate_token
        with:
          app_id: ${{ secrets.RELEASE_PLEASE_ACTION_ID }}
          private_key: ${{ secrets.RELEASE_PLEASE_ACTION_PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          release-type: simple
