name: Auto approve
on:
  workflow_run:
    workflows:
      - "Build Check"
      - "reviewdog"
    types:
      - completed

permissions: write-all
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: contains(fromJSON('["misumisumi"]'), github.actor)
    steps:
      # From https://github.com/orgs/community/discussions/25220#discussioncomment-8697399
      - uses: actions/github-script@v7
        id: pr
        with:
          script: |
            const response = await github.rest.search.issuesAndPullRequests({
              q: 'repo:${{ github.repository }} is:pr sha:${{ github.event.workflow_run.head_sha }}',
              per_page: 1,
            })
            const items = response.data.items
            if (items.length < 1) {
              console.error('No PRs found')
              return
            }
            const pullRequestNumber = items[0].number
            console.info("Pull request number is", pullRequestNumber)
            return pullRequestNumber

      - name: Check workflow status
        id: check-workflow-status
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          PR_NUM: ${{ steps.pr.outputs.result }}
        run: |
          status_check=$(gh pr view "${PR_NUM}" --json statusCheckRollup)
          completed=$(echo $status_check | jq -r '.statusCheckRollup | [.[] | select(.status=="COMPLETED")]')
          if [ $(echo $completed | jq -r '. | length' ) -eq $(echo $status_check | jq -r '.statusCheckRollup | length') ]; then
            if [ $(echo $completed | jq '[.[].conclusion] | all(.=="SUCCESS" or "NEUTRAL")') = true ]; then
              gh pr review --approve "${PR_NUM}"
            fi
          fi
